#!/bin/bash


config="$HOME/dotfiles"

declare -a config_config=(

"$config/.config/fish"
"$config/.config/kitty"
"$config/.config/nvim"
"$config/.config/myzsh/aliases.sh"
"$config/.config/qtile"
"$config/.config/qutebrowser"
"$config/.config/rofi"
"$config/.config/starship.toml"

)

declare -a config_home=(

"$config/.tmux.conf.local"
"$config/.xmonad"
"$config/.zshrc"


)
declare -a config_sudo=(

"$config/.config/lightdm"

)





for cc in "${config_config[@]}" ; do

    printf "\n$cc"

done


